import type { Appeal, Department, DocumentCategory, StatItem } from './types'

export const stats: StatItem[] = [
  {
    label: 'Jami murojaatlar',
    value: 1247,
    change: 12,
    icon: 'FileText',
    color: 'blue',
  },
  {
    label: "Ko'rib chiqilmoqda",
    value: 89,
    change: -5,
    icon: 'Clock',
    color: 'amber',
  },
  {
    label: 'Tugatilgan',
    value: 1089,
    change: 18,
    icon: 'CheckCircle',
    color: 'emerald',
  },
  {
    label: "Muddati o'tgan",
    value: 23,
    change: -8,
    icon: 'AlertTriangle',
    color: 'rose',
  },
]

export const documentCategories: DocumentCategory[] = [
  {
    type: 'talabalik_guvohnomasi',
    title: 'Talabalik guvohnomasi',
    description: 'Talabalik holatini tasdiqlovchi hujjat',
    count: 156,
    icon: 'GraduationCap',
    color: 'blue',
  },
  {
    type: 'oquv_varaqasi',
    title: "O'quv varaqasi",
    description: "Talabaning o'quv natijalari va baholari",
    count: 203,
    icon: 'BookOpen',
    color: 'violet',
  },
  {
    type: 'malumotnoma',
    title: "O'qish joyidan ma'lumotnoma",
    description: "O'qish joyi haqida rasmiy ma'lumot",
    count: 178,
    icon: 'Building2',
    color: 'cyan',
  },
  {
    type: 'akademik_malumotnoma',
    title: "Akademik ma'lumotnoma",
    description: 'Akademik kreditlar va transkript',
    count: 134,
    icon: 'Award',
    color: 'indigo',
  },
  {
    type: 'dars_jadvali',
    title: 'Dars jadvali',
    description: "Semestr bo'yicha dars jadvali",
    count: 312,
    icon: 'Calendar',
    color: 'orange',
  },
  {
    type: 'davomat',
    title: "Davomat va o'zlashtirish",
    description: "Davomat va o'zlashtirish ko'rsatkichlari",
    count: 89,
    icon: 'BarChart3',
    color: 'teal',
  },
  {
    type: 'shartnoma',
    title: "To'lov-kontrakt shartnoma",
    description: 'Talaba bilan tuzilgan shartnomalar',
    count: 245,
    icon: 'FileSignature',
    color: 'emerald',
  },
  {
    type: 'turar_joy',
    title: 'Turar joy arizasi',
    description: "Yotoqxona va turar joyga arizalar",
    count: 67,
    icon: 'Home',
    color: 'pink',
  },
  {
    type: 'aylanma_varaqa',
    title: 'Aylanma varaqalar',
    description: 'Raqamlashtirilgan aylanma hujjatlar',
    count: 421,
    icon: 'FolderOpen',
    color: 'slate',
  },
]

export const departments: Department[] = [
  {
    id: 'registrator',
    name: 'Registrator ofisi',
    shortName: 'Registrator',
    pending: 34,
    completed: 412,
    color: 'blue',
  },
  {
    id: 'uslubiy',
    name: "O'quv-uslubiy boshqarma",
    shortName: "O'quv-uslubiy",
    pending: 12,
    completed: 189,
    color: 'violet',
  },
  {
    id: 'dekanat',
    name: 'Dekanatlar',
    shortName: 'Dekanat',
    pending: 28,
    completed: 356,
    color: 'indigo',
  },
  {
    id: 'buxgalteriya',
    name: 'Buxgalteriya',
    shortName: 'Buxgalteriya',
    pending: 8,
    completed: 245,
    color: 'emerald',
  },
  {
    id: 'marketing',
    name: 'Marketing va amaliyot',
    shortName: 'Marketing',
    pending: 5,
    completed: 98,
    color: 'orange',
  },
  {
    id: 'ilmiy',
    name: 'Ilmiy bo\'lim',
    shortName: 'Ilmiy',
    pending: 3,
    completed: 67,
    color: 'cyan',
  },
  {
    id: 'xalqaro',
    name: 'Xalqaro aloqalar',
    shortName: 'Xalqaro',
    pending: 7,
    completed: 112,
    color: 'rose',
  },
]

export const appeals: Appeal[] = [
  {
    id: 'M-2026-1847',
    student: 'Abdullayev Jasur',
    faculty: 'Pedagogika fakulteti',
    documentType: 'talabalik_guvohnomasi',
    department: 'Registrator ofisi',
    status: 'jarayonda',
    createdAt: '2026-07-12',
    deadline: '2026-07-16',
    progress: 65,
  },
  {
    id: 'M-2026-1846',
    student: 'Karimova Nodira',
    faculty: 'Til va adabiyot',
    documentType: 'akademik_malumotnoma',
    department: 'Dekanat',
    status: 'yangi',
    createdAt: '2026-07-14',
    deadline: '2026-07-18',
    progress: 10,
  },
  {
    id: 'M-2026-1845',
    student: 'Rahimov Bobur',
    faculty: 'Ijtimoiy fanlar',
    documentType: 'shartnoma',
    department: 'Buxgalteriya',
    status: 'kechikkan',
    createdAt: '2026-07-08',
    deadline: '2026-07-12',
    progress: 80,
  },
  {
    id: 'M-2026-1844',
    student: 'Saidova Malika',
    faculty: 'Psixologiya',
    documentType: 'turar_joy',
    department: 'Registrator ofisi',
    status: 'jarayonda',
    createdAt: '2026-07-13',
    deadline: '2026-07-17',
    progress: 45,
  },
  {
    id: 'M-2026-1843',
    student: 'Toshpulatov Alisher',
    faculty: 'Matematika',
    documentType: 'dars_jadvali',
    department: "O'quv-uslubiy boshqarma",
    status: 'tugallangan',
    createdAt: '2026-07-10',
    deadline: '2026-07-14',
    progress: 100,
  },
  {
    id: 'M-2026-1842',
    student: 'Usmonova Dilnoz',
    faculty: 'Tarix',
    documentType: 'oquv_varaqasi',
    department: 'Registrator ofisi',
    status: 'jarayonda',
    createdAt: '2026-07-11',
    deadline: '2026-07-15',
    progress: 55,
  },
  {
    id: 'M-2026-1841',
    student: 'Xolmatov Sanjar',
    faculty: 'Jismoniy tarbiya',
    documentType: 'davomat',
    department: 'Dekanat',
    status: 'yangi',
    createdAt: '2026-07-15',
    deadline: '2026-07-19',
    progress: 5,
  },
  {
    id: 'M-2026-1840',
    student: 'Ergasheva Feruza',
    faculty: 'Xalqaro aloqalar',
    documentType: 'malumotnoma',
    department: 'Xalqaro aloqalar',
    status: 'tugallangan',
    createdAt: '2026-07-09',
    deadline: '2026-07-13',
    progress: 100,
  },
]

export const weeklyStats = [
  { day: 'Dush', received: 42, completed: 38 },
  { day: 'Sesh', received: 55, completed: 48 },
  { day: 'Chor', received: 38, completed: 41 },
  { day: 'Pay', received: 61, completed: 52 },
  { day: 'Jum', received: 47, completed: 44 },
  { day: 'Shan', received: 23, completed: 28 },
  { day: 'Yak', received: 12, completed: 15 },
]
